### ISSUE TITLE
data header format

### ISSUE THREAD

**Issue by courtneyum** [gharveymn/matshare#5]
We need to store meta info in a header in each shared memory object, so we will need to come up with a good header that can make fetching any data type simple, including complicated structs and cell arrays.

Does each element of a cell array need to have a type header?
Or can we ignore the type and just use mxGetCell for each element and copy each element over to the shared memory directly using memcpy? Then to fetch maybe use mxCreateCellArray and mxSetCell to get directly without the need for any intermediate c types?

**Comment by gharveymn** [comment]
Yeah I was thinking we should probably just use the mxArray opaque type directly. It acts pretty much as a header itself, so we can just place that at the top of the shared memory segment. Each object in MATLAB gets its own mxArray, so like if you have a cell array full of doubles you would have something like mxArray(mxCELL_CLASS) -> mxArray(mxDOUBLE_CLASS) -> raw_data, where you fetch the mxDOUBLE_CLASS mxArray via an API call. So basically we would need to open shm, place each one of the components (mxArrays and raw data) into the segment and then redirect the pointers in each of the mxArrays to the new locations
